# Generated by Django 3.2.12 on 2022-04-11 12:35

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220406_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleruser',
            name='user_name',
            field=models.CharField(default='Username', max_length=60),
        ),
        migrations.AlterField(
            model_name='scheduleruser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
